services:
  api:
    build:
      dockerfile: Dockerfile.prod
    environment:
      DATABASE_URL: postgres-tests
      NODE_ENV: test

  postgres-tests:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: tests
