services:
  web:
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    build:
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${WEB_PORT}
      NODE_ENV: development
    volumes:
      - ./frontend:/web

  api:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PORT: ${API_PORT}
      NODE_ENV: development
    volumes:
      - ./backend:/api
