version: "3.9"
services:
  web:
    build:
      context: ./frontend
    container_name: web

  api:
    container_name: api
    environment:
      DATABASE_URL: db
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
    build:
      context: ./backend
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    expose:
      - 5342
    volumes:
      - pg-data:/var/lib/postgresql/data/

volumes:
  pg-data:
