services:

  # TODO remove volume usage on production
  # TODO create yarn script for production
  web:
    restart: always
    command: sh -c "${INSTALL_PYTHON} && yarn && yarn build && yarn global add serve && serve -s build"
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      PORT: ${WEB_PORT}
    working_dir: /web

  api:
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}

  db:
    restart: always
