version: "3.8"
services:
  api:
    image: node:14-alpine
    command: sh -c "yarn && yarn setup-db && yarn dev"
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=db
    working_dir: /api
    volumes:
      - ./:/api
    depends_on:
      - db

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data/

volumes:
  pg-data:
